INSERT INTO T_STUDENT (F_ID, F_FIRSTNAME, F_LASTNAME, F_BIRTHDATE) VALUES (hibernate_sequence.nextval, 'SAMI', 'KARAM', null);
INSERT INTO T_STUDENT (F_ID, F_FIRSTNAME, F_LASTNAME, F_BIRTHDATE) VALUES (hibernate_sequence.nextval, 'GEORGES', 'KHOURY', null);
INSERT INTO T_STUDENT (F_ID, F_FIRSTNAME, F_LASTNAME, F_BIRTHDATE) VALUES (hibernate_sequence.nextval, 'ALI', 'AHMAD', null);
INSERT INTO T_STUDENT (F_ID, F_FIRSTNAME, F_LASTNAME, F_BIRTHDATE) VALUES (hibernate_sequence.nextval, 'ZEINA', 'HJEIJ', null);
INSERT INTO T_STUDENT (F_ID, F_FIRSTNAME, F_LASTNAME, F_BIRTHDATE) VALUES (hibernate_sequence.nextval, 'YOUSSEF', 'KAHWAJI', null);
INSERT INTO T_STUDENT (F_ID, F_FIRSTNAME, F_LASTNAME, F_BIRTHDATE) VALUES (hibernate_sequence.nextval, 'NANCY', 'AJRAM', null);